[package]
name = "rust-wasm-memory-import-hello-world"
version = "0.1.0"
authors = ["petrkosikhin"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
